web/router.ex
defmodule ScutworthsFabulousLendingLibrary.Router do
  use ScutworthsFabulousLendingLibrary.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ScutworthsFabulousLendingLibrary do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/books", BookController
    resources "/borrowers", BorrowerController
    resources "/checkouts", CheckoutController
  end

  # Other scopes may use custom stacks.
  # scope "/api", ScutworthsFabulousLendingLibrary do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule ScutworthsFabulousLendingLibrary.LayoutView do
  use ScutworthsFabulousLendingLibrary.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Scutworth's Fabulous Lending Library</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.1/css/bootstrap-datepicker3.min.css">

    <script src="https://code.jquery.com/jquery-2.2.4.min.js" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.1/js/bootstrap-datepicker.min.js"></script>
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="/">Home</a></li>
            <li><%= link "Books", to: book_path(@conn, :index) %></li>
            <li><%= link "Borrowers", to: borrower_path(@conn, :index) %></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info"   role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-warn"   role="alert"><%= get_flash(@conn, :warn) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/form.js") %>"></script>
  </body>
</html>